apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-platform-apps
  namespace: platform
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/devops-saas-platform
    targetRevision: HEAD
    path: kubernetes/overlays/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true