apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/applications

namePrefix: prod-

namespace: platform

# patchesStrategicMerge:
# - path: example-app-resources.yaml
#   target:
#     kind: Deployment
#     name: example-app