server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: container-logs
          __path__: /var/log/containers/*multitenant*.log
    pipeline_stages:
      - match:
          selector: '{job="container-logs"}'
          stages:
            - cri: {}
            - template:
                source: output
                template: "{{ .Output }}"
            - labeldrop:
                - filename
      - match:
          selector: '{job="container-logs", app="multitenant-api"}'
          stages:
            - json:
                expressions:
                  level: level
                  message: message
                  tenant_id: "tenant_id"
            - labels:
                level:
                tenant_id: